import type { Content, Recipe, Text } from "../../CommonAdvanced/src/types";
const text = (cs: string, en: string): Text => ({ cs, en });
const meal = (
  id: string,
  cs: string,
  en: string,
  ingredients: Record<string, number>,
  price: number,
  color: string,
  cold = false,
): Recipe => ({
  id,
  name: text(cs, en),
  kind: "meal",
  ingredients,
  price,
  color,
  steps: cold
    ? [{ capability: "prep", seconds: 2 }]
    : [
        { capability: "prep", seconds: 2 },
        { capability: "heat", seconds: 4 },
      ],
});
const drink = (
  id: string,
  cs: string,
  en: string,
  ingredients: Record<string, number>,
  price: number,
  color: string,
): Recipe => ({
  id,
  name: text(cs, en),
  kind: "drink",
  ingredients,
  price,
  color,
  steps: [{ capability: "bar", seconds: 2 }],
});
export const content: Content = {
  layout: {
    areas: [
      { minX: -8.25, maxX: 8.25, minZ: -7.75, maxZ: 11.9 },
      { minX: 7.75, maxX: 10.25, minZ: 2, maxZ: 12, unlock: 9 },
    ],
    obstacles: [
      { unlock: 3, x: -7, z: 8, hw: 0.85, hd: 0.38 },
      { unlock: 4, x: -7.7, z: -2, hw: 0.5, hd: 0.75 },
      { unlock: 6, x: 6, z: 0, hw: 0.6, hd: 0.4 },
      { unlock: 8, x: -7, z: 10, hw: 0.8, hd: 0.4 },
      { unlock: 10, x: 7, z: -2, hw: 0.7, hd: 0.5 },
      ...[
        [-8, 3],
        [-8, 11],
        [7.8, 11],
        [7.8, 2],
      ].map(([x, z]) => ({ x, z, r: 0.45 })),
      ...[2, 12].map((z) => ({ x: 9.5, z, r: 0.45, unlock: 9 })),
      ...[-2, 2].map((x) => ({ x, z: 11.3, r: 0.18, unlock: 12 })),
    ],
  },
  id: "world",
  ingredients: [
    { id: "chicken", name: text("Kuře", "Chicken"), cost: 4 },
    { id: "beef", name: text("Hovězí", "Beef"), cost: 5 },
    { id: "potato", name: text("Brambory", "Potatoes"), cost: 1 },
    { id: "vegetable", name: text("Zelenina", "Vegetables"), cost: 2 },
    { id: "rice", name: text("Rýže", "Rice"), cost: 1 },
    { id: "noodle", name: text("Nudle", "Noodles"), cost: 2 },
    { id: "lentil", name: text("Čočka", "Lentils"), cost: 2 },
    { id: "spice", name: text("Koření", "Spices"), cost: 1 },
    { id: "lemon", name: text("Citrony", "Lemons"), cost: 1 },
    { id: "milk", name: text("Mléko", "Milk"), cost: 1 },
    { id: "coffee", name: text("Káva", "Coffee"), cost: 1 },
    { id: "tea", name: text("Čaj", "Tea"), cost: 1 },
  ],
  styles: [
    {
      id: "bistro",
      name: text("Evropské bistro", "European bistro"),
      color: "#b86642",
      recipes: [
        meal(
          "roast",
          "Kuře s bramborami",
          "Roast chicken",
          { chicken: 1, potato: 2 },
          27,
          "#bb703e",
        ),
        meal(
          "soup",
          "Zeleninová polévka",
          "Vegetable soup",
          { vegetable: 2, potato: 1 },
          22,
          "#dfab55",
        ),
        meal(
          "salad",
          "Zahradní salát",
          "Garden salad",
          { vegetable: 2 },
          19,
          "#75a653",
          true,
        ),
        drink("coffee", "Káva", "Coffee", { coffee: 1, milk: 1 }, 9, "#704a31"),
        drink("lemonade", "Limonáda", "Lemonade", { lemon: 2 }, 8, "#f4d977"),
      ],
    },
    {
      id: "diner",
      name: text("Americký diner", "American diner"),
      color: "#d57948",
      recipes: [
        meal(
          "steak",
          "Steak s bramborami",
          "Steak and potatoes",
          { beef: 1, potato: 2 },
          30,
          "#954c35",
        ),
        meal(
          "grilled",
          "Grilované kuře",
          "Grilled chicken",
          { chicken: 1, vegetable: 1 },
          27,
          "#c28548",
        ),
        meal(
          "veggie",
          "Zeleninový talíř",
          "Vegetable plate",
          { vegetable: 2, potato: 1 },
          22,
          "#7f9f52",
        ),
        drink("shake", "Milkshake", "Milkshake", { milk: 2 }, 10, "#f1d5bd"),
        drink("dinerlemon", "Limonáda", "Lemonade", { lemon: 2 }, 8, "#f4d977"),
      ],
    },
    {
      id: "wok",
      name: text("Wok bistro", "Wok bistro"),
      color: "#b65043",
      recipes: [
        meal(
          "wokchicken",
          "Kuřecí wok s rýží",
          "Chicken rice wok",
          { chicken: 1, rice: 1, vegetable: 1 },
          28,
          "#ad7748",
        ),
        meal(
          "woknoodle",
          "Zeleninové nudle",
          "Vegetable noodles",
          { noodle: 1, vegetable: 2 },
          24,
          "#d2b975",
        ),
        meal(
          "friedrice",
          "Smažená rýže",
          "Fried rice",
          { rice: 2, vegetable: 1 },
          21,
          "#e0cb8c",
        ),
        drink("hottea", "Horký čaj", "Hot tea", { tea: 1 }, 7, "#b69752"),
        drink(
          "icedtea",
          "Ledový čaj",
          "Iced tea",
          { tea: 1, lemon: 1 },
          9,
          "#d69e48",
        ),
      ],
    },
    {
      id: "curry",
      name: text("Indické bistro", "Indian bistro"),
      color: "#b88b38",
      recipes: [
        meal(
          "chickencurry",
          "Kuřecí kari",
          "Chicken curry",
          { chicken: 1, rice: 1, spice: 1 },
          28,
          "#d88739",
        ),
        meal(
          "vegetablecurry",
          "Zeleninové kari",
          "Vegetable curry",
          { vegetable: 2, rice: 1, spice: 1 },
          25,
          "#c89b3c",
        ),
        meal(
          "dal",
          "Dal s rýží",
          "Dal and rice",
          { lentil: 2, rice: 1, spice: 1 },
          23,
          "#d9ae4d",
        ),
        drink(
          "chai",
          "Chai",
          "Chai",
          { tea: 1, milk: 1, spice: 1 },
          10,
          "#c69d70",
        ),
        drink("lassi", "Lassi", "Lassi", { milk: 2 }, 10, "#f4e7ce"),
      ],
    },
  ],
  stations: [
    {
      id: "source",
      name: text("Sklad", "Stockroom"),
      capability: "source",
      x: -6,
      z: -5,
    },
    {
      id: "prep",
      name: text("Příprava", "Preparation"),
      capability: "prep",
      x: -2,
      z: -5,
    },
    {
      id: "heat",
      name: text("Vaření", "Cooking"),
      capability: "heat",
      x: 2,
      z: -5,
    },
    {
      id: "bar",
      name: text("Nápoje", "Drinks"),
      capability: "bar",
      x: 6,
      z: -5,
    },
    {
      id: "pass",
      name: text("Kompletace", "Plating"),
      capability: "pass",
      x: 3,
      z: 0,
    },
    {
      id: "wash",
      name: text("Mytí nádobí", "Dishwashing"),
      capability: "wash",
      x: -6,
      z: 0,
    },
  ],
  tables: [
    { x: -4, z: 5 },
    { x: 0, z: 5 },
    { x: 4, z: 5 },
    { x: -4, z: 9 },
    { x: 0, z: 9 },
    { x: 4, z: 9 },
    { x: 8, z: 5 },
    { x: 8, z: 9 },
  ],
  expansions: [
    {
      id: 1,
      name: text("Třetí stůl", "Third table"),
      description: text(
        "Další hosté v hlavní jídelně.",
        "More guests in the main dining room.",
      ),
      cost: 90,
      tables: 1,
    },
    {
      id: 2,
      name: text("Zahradní posezení", "Garden seating"),
      description: text("První stůl na terase.", "The first terrace table."),
      cost: 120,
      tables: 1,
    },
    {
      id: 3,
      name: text("Šatna týmu", "Team room"),
      description: text(
        "Dvě další místa pro zaměstnance.",
        "Two more employee slots.",
      ),
      cost: 180,
      staff: 2,
    },
    {
      id: 4,
      name: text("Velký sklad", "Large stockroom"),
      description: text(
        "Další regály a prostor pro suroviny.",
        "More shelves and ingredient capacity.",
      ),
      cost: 220,
      storage: 40,
    },
    {
      id: 5,
      name: text("Dlouhá terasa", "Long terrace"),
      description: text(
        "Další zahradní stůl a talíře.",
        "Another terrace table and plates.",
      ),
      cost: 280,
      tables: 1,
      plates: 2,
    },
    {
      id: 6,
      name: text("Velký tác", "Large tray"),
      description: text(
        "Dvě místa navíc a odkládací vozík.",
        "Two more tray slots and a serving trolley.",
      ),
      cost: 330,
      capacity: 2,
    },
    {
      id: 7,
      name: text("Rodinné posezení", "Family seating"),
      description: text(
        "Šestý stůl a nový květinový záhon.",
        "A sixth table and a new flower bed.",
      ),
      cost: 420,
      tables: 1,
    },
    {
      id: 8,
      name: text("Profesionální zázemí", "Professional workspace"),
      description: text(
        "Dvě místa v týmu a zásoba nádobí.",
        "Two employee slots and more plates.",
      ),
      cost: 500,
      staff: 2,
      plates: 4,
    },
    {
      id: 9,
      name: text("Východní jídelna", "East dining room"),
      description: text(
        "Sedmý stůl ve vlastním křídle.",
        "A seventh table in its own wing.",
      ),
      cost: 620,
      tables: 1,
    },
    {
      id: 10,
      name: text("Zásobovací křídlo", "Supply wing"),
      description: text(
        "Více surovin a další člen týmu.",
        "More ingredients and another employee slot.",
      ),
      cost: 720,
      storage: 60,
      staff: 1,
    },
    {
      id: 11,
      name: text("Zahradní salonek", "Garden lounge"),
      description: text(
        "Osmý stůl a nové osvětlení.",
        "An eighth table and garden lighting.",
      ),
      cost: 850,
      tables: 1,
    },
    {
      id: 12,
      name: text("Vlajková restaurace", "Flagship restaurant"),
      description: text(
        "Zlaté ocenění, tým a největší sklad.",
        "Golden award, a larger team and stockroom.",
      ),
      cost: 1000,
      staff: 2,
      storage: 40,
      plates: 4,
    },
  ],
};
